package edu.secourse.patientportal.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing a scheduled appointment between a {@link Patient} and a {@link Doctor}.
 *
 * <p>This class models appointment data including participants, timing,
 * and status. It is mapped to the {@code appointments} table and uses
 * JPA relationships to link patients and doctors.
 *
 * <p><b>Persistence Details:</b>
 * <ul>
 *     <li>Mapped to {@code appointments} table</li>
 *     <li>Uses {@link ManyToOne} relationships for Patient and Doctor</li>
 *     <li>Primary key is auto-generated</li>
 * </ul>
 *
 * <p><b>Core Responsibilities:</b>
 * <ul>
 *     <li>Store appointment scheduling data</li>
 *     <li>Track appointment status</li>
 *     <li>Maintain modification timestamps</li>
 * </ul>
 */
@Entity
@Table(name = "appointments")
public class Appointment {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer appointmentId;

    /** Patient associated with the appointment. */
    @ManyToOne
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    /** Doctor associated with the appointment. */
    @ManyToOne
    @JoinColumn(name = "doctor_id", nullable = false)
    private Doctor doctor;

    /** Start time of the appointment. */
    @Column(name = "start_time", nullable = false)
    private LocalDateTime appointmentDateTime;

    /** End time of the appointment. */
    @Column(name = "end_time")
    private LocalDateTime endTime;

    /** Timestamp of the last modification. */
    @Column(name = "last_updated")
    private LocalDateTime lastUpdated;

    /** Current status of the appointment. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20)
    private Status status = Status.UNSPECIFIED;

    public void setAppointmentId(int i) {
        this.appointmentId = i;
    }

    /**
     * Enumeration representing possible appointment states.
     */
    public enum Status {
        ACTIVE,
        CANCELLED,
        UNSPECIFIED
    }

    /** Default constructor required by JPA. */
    public Appointment() {}

    /**
     * Constructs an appointment with required fields.
     *
     * <p>Automatically sets:
     * <ul>
     *     <li>End time to 30 minutes after start time</li>
     *     <li>Status to {@link Status#ACTIVE}</li>
     *     <li>Last updated timestamp</li>
     * </ul>
     *
     * @param patient appointment patient
     * @param doctor appointment doctor
     * @param appointmentDateTime appointment start time
     */
    public Appointment(Patient patient, Doctor doctor, LocalDateTime appointmentDateTime) {
        if (patient != null && doctor != null && appointmentDateTime != null) {
            this.patient = patient;
            this.doctor = doctor;
            this.appointmentDateTime = appointmentDateTime;
            this.endTime = appointmentDateTime.plusMinutes(30);
            this.lastUpdated = LocalDateTime.now();
            this.status = Status.ACTIVE;
        }
    }

    /**
     * Gets the appointment ID.
     *
     * @return appointment ID or 0 if not persisted
     */
    public int getAppointmentId() {
        return appointmentId != null ? appointmentId : 0;
    }

    /**
     * Gets the patient.
     *
     * @return associated patient
     */
    public Patient getPatient() {
        return patient;
    }

    /**
     * Sets the patient and updates modification timestamp.
     *
     * @param patient new patient
     */
    public void setPatient(Patient patient) {
        if (patient != null) {
            this.patient = patient;
            this.lastUpdated = LocalDateTime.now();
        }
    }

    /**
     * Gets the doctor.
     *
     * @return associated doctor
     */
    public Doctor getDoctor() {
        return doctor;
    }

    /**
     * Sets the doctor and updates modification timestamp.
     *
     * @param doctor new doctor
     */
    public void setDoctor(Doctor doctor) {
        if (doctor != null) {
            this.doctor = doctor;
            this.lastUpdated = LocalDateTime.now();
        }
    }

    /**
     * Gets the appointment start time.
     *
     * @return start time
     */
    public LocalDateTime getAppointmentDateTime() {
        return appointmentDateTime;
    }

    /**
     * Updates appointment start time and recalculates end time.
     *
     * @param appointmentDateTime new start time
     */
    public void setAppointmentDateTime(LocalDateTime appointmentDateTime) {
        if (appointmentDateTime != null) {
            this.appointmentDateTime = appointmentDateTime;
            this.endTime = appointmentDateTime.plusMinutes(30);
            this.lastUpdated = LocalDateTime.now();
        }
    }

    /**
     * Gets the end time.
     *
     * @return end time
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * Sets the end time.
     *
     * @param endTime new end time
     */
    public void setEndTime(LocalDateTime endTime) {
        if (endTime != null) {
            this.endTime = endTime;
            this.lastUpdated = LocalDateTime.now();
        }
    }

    /**
     * Gets the appointment status.
     *
     * @return current status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the appointment status.
     *
     * @param status new status
     */
    public void setStatus(Status status) {
        if (status != null) {
            this.status = status;
        }
    }

    /**
     * Gets last updated timestamp.
     *
     * @return last update time
     */
    public LocalDateTime getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Cancels the appointment.
     *
     * <p>Sets status to {@link Status#CANCELLED}.
     */
    public void cancelAppointment() {
        this.status = Status.CANCELLED;
        this.lastUpdated = LocalDateTime.now();
    }

    /**
     * Returns a readable string representation of the appointment.
     *
     * @return formatted appointment string
     */
    @Override
    public String toString() {
        String patientName = (patient != null) ? patient.getUsername() : "Unknown Patient";
        String doctorName = (doctor != null) ? doctor.getUsername() : "Unknown Doctor";

        return "Appointment{" +
                "id=" + appointmentId +
                ", patient='" + patientName + '\'' +
                ", doctor='" + doctorName + '\'' +
                ", start=" + appointmentDateTime +
                ", end=" + endTime +
                ", status=" + status +
                '}';
    }
}