package edu.secourse.patientportal.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Base entity representing a user in the patient portal system.
 *
 * <p>This class serves as the parent for all user types (Patient, Doctor, Admin)
 * and is mapped to a single database table using JPA single-table inheritance.
 *
 * <p><b>Persistence Details:</b>
 * <ul>
 *     <li>Mapped to {@code users} table</li>
 *     <li>Uses {@link InheritanceType#SINGLE_TABLE} strategy</li>
 *     <li>Role is managed via {@link DiscriminatorColumn}</li>
 * </ul>
 *
 * <p><b>Core Responsibilities:</b>
 * <ul>
 *     <li>Stores authentication data (username, password)</li>
 *     <li>Stores user identity (name, email)</li>
 *     <li>Tracks security timestamps (login, password changes)</li>
 * </ul>
 *
 * <p><b>Inheritance:</b>
 * <ul>
 *     <li>{@link Patient}</li>
 *     <li>{@link Doctor}</li>
 *     <li>{@link Admin}</li>
 * </ul>
 */
@Entity
@Data
@SuperBuilder
@Table(name = "users")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "role", discriminatorType = DiscriminatorType.STRING)
@AllArgsConstructor
@NoArgsConstructor
public class User {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /** Unique username used for authentication. */
    @Column(name = "username", unique = true, nullable = false, length = 100)
    private String username;

    /** Hashed password stored securely (e.g., BCrypt). */
    @Column(name = "password", nullable = false)
    private String password;

    /** User's first name. */
    @Column(name = "first_name", length = 100)
    private String firstName;

    /** User's last name. */
    @Column(name = "last_name", length = 100)
    private String lastName;

    /** Full name (used for display purposes). */
    @Column(name = "name", length = 200)
    private String name;

    /** Unique email address. */
    @Column(name = "email", unique = true, length = 200)
    private String email;

    /**
     * Role discriminator column managed by JPA.
     * Not directly insertable or updatable.
     */
    @Column(name = "role", insertable = false, updatable = false)
    private String role;

    /** Timestamp of last successful login. */
    @Column(name = "last_login")
    private LocalDateTime lastLogin;

    /** Timestamp of last password change. */
    @Column(name = "last_password_change")
    private LocalDateTime lastPasswordChange;

    /**
     * Constructs a User with core attributes.
     *
     * <p>Automatically splits full name into first and last name.
     *
     * @param username username
     * @param password hashed password
     * @param name full name
     * @param email email address
     * @param role user role
     */
    public User(String username, String password, String name, String email, String role) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.email = email;
        this.role = role.toUpperCase();

        if (name != null && !name.isBlank()) {
            String[] parts = name.trim().split("\\s+", 2);
            this.firstName = parts[0];
            this.lastName = (parts.length > 1) ? parts[1] : "";
        }
    }

    /**
     * Updates the user's password and records the change timestamp.
     *
     * @param hashedPassword new hashed password
     */
    public void setPassword(String hashedPassword) {
        this.password = hashedPassword;
        this.lastPasswordChange = LocalDateTime.now();
    }

    /**
     * Updates the user's full name and splits into first and last name.
     *
     * @param name new full name
     */
    public void setName(String name) {
        this.name = name;

        if (name != null && !name.isBlank()) {
            String[] parts = name.trim().split("\\s+", 2);
            this.firstName = parts[0];
            this.lastName = (parts.length > 1) ? parts[1] : "";
        }
    }

    /**
     * Records the current timestamp as last login.
     */
    public void recordLogin() {
        this.lastLogin = LocalDateTime.now();
    }

    /**
     * Retrieves the user's role.
     *
     * <p>If role is null, it is inferred from subclass type.
     *
     * @return normalized role string
     */
    public String getRole() {
        if (role != null) return role.toUpperCase();
        if (this instanceof Patient) return "PATIENT";
        if (this instanceof Doctor) return "DOCTOR";
        if (this instanceof Admin) return "ADMIN";
        return "UNKNOWN";
    }

    /**
     * Sets the user's role.
     *
     * @param role role string
     */
    public void setRole(String role) {
        this.role = role.toUpperCase();
    }

    /**
     * Equality based on username.
     *
     * @param o object to compare
     * @return true if usernames match
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof User user)) return false;
        return Objects.equals(username, user.username);
    }

    /**
     * Hash code based on username.
     *
     * @return hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(username);
    }

    /**
     * String representation of user.
     *
     * @return user details string
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", role='" + role + '\'' +
                ", lastLogin=" + lastLogin +
                ", lastPasswordChange=" + lastPasswordChange +
                '}';
    }
}